database:
  hostName: ${DB_HOST}
  hostPort: ${DB_PORT}
  databaseName: ${DB_NAME}
  privilegedDatabaseUser: ${DB_USER}
  privilegedDatabasePassword: ${DB_PASSWORD}
  useSameDbUserForOrangeHRM: y # y/n, if this field `n` fill `orangehrmDatabaseUser` and `orangehrmDatabasePassword`
  orangehrmDatabaseUser: ~
  orangehrmDatabasePassword: ~
  isExistingDatabase: n # y/n
  enableDataEncryption: n # y/n

organization:
  name: ${OHRM_ORGANIZATION_NAME}
  country: ${OHRM_COUNTRY}

admin:
  adminUserName: ${OHRM_ADMIN_USERNAME}
  adminPassword: ${OHRM_ADMIN_PASSWORD}
  adminEmployeeFirstName: OrangeHRM
  adminEmployeeLastName: Admin
  workEmail: ${OHRM_ADMIN_EMAIL}
  contactNumber: ~
  registrationConsent: true

license:
  agree: y # y/n
